### PR TITLE
Subscribe to state on CBScheduler

### PR DESCRIPTION
**Pull request by indragiek**
I'm not 100% sure on this, but I think the state subscription should be handled on the `CBScheduler` (like all of the other delegate method subscriptions) because delegate method calls should be processed in a serial order.

### CODE REVIEW

**Comment by kastiglione** [comment]
> because delegate method calls should be processed in a serial order

Then you would want `-deliverOn:`, no?

**Comment by indragiek** [comment]
I might have phrased that poorly, I was referring to the subscription itself and not the scheduler on which values are delivered to the subscriber. I just realized that `-rac_signalForSelector:` will send values on the thread from which the delegate method was invoked on regardless, so that won't be an issue, but the real problem here is the call to `manager.state` inside the `-map:` block. Reading that value on something other than `CBScheduler` could lead to potential race conditions. I would need `-subscribeOn:` to resolve that, correct?

**Comment by kastiglione** [comment]
In that case I would say apply `deliverOn:self.CBScheduler` to `return:self.manager`. Yes, you could also go with `-subscribeOn:`, since `+return:` sends its value synchronously on subscription, but I would argue that `-deliverOn:` is better semantically because the subsequent `-map:` is about delivery.

**Comment by indragiek** [comment]
Elegant! Will do.

**Comment by indragiek** [comment]
:boom:

**Pull request merged**
