### PR TITLE
State restoration signal

### PR DESCRIPTION
**Pull request by indragiek**
This doesn't feel very FRP-ish but I'm not sure if there's any better way to do this.

### CODE REVIEW

**Comment by kastiglione** [comment]
> This doesn't feel very FRP-ish

Why's that? What don't you like?

**Comment by indragiek** [comment]
I'm pretty sure I'm just over thinking it. It just didn't seem _that_ useful exposing it as a signal when it did nothing more than wrap an existing delegate call, but I suppose it still provides some benefit in the ability to have multiple objects subscribing to the event (and composability of signals, of course).

**Comment by kastiglione** [comment]
> composability of signals, of course

I agree, looks sound to me.

**Comment by indragiek** [comment]
:+1: Good to merge?

**Comment by kastiglione** [comment]
Yep.

**Pull request merged**
